// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQo3hpYy4lKJXqbiUgtCQJ3NBj1qZ1u60',
    appId: '1:257163398101:web:f92660cca3d7df707e8b5c',
    messagingSenderId: '257163398101',
    projectId: 'notes-flutter-290323',
    authDomain: 'notes-flutter-290323.firebaseapp.com',
    storageBucket: 'notes-flutter-290323.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh-hukXSV6a_Kiuyk2ItcM6HXgj7wurCc',
    appId: '1:257163398101:android:d4b19f7c8bb8cab37e8b5c',
    messagingSenderId: '257163398101',
    projectId: 'notes-flutter-290323',
    storageBucket: 'notes-flutter-290323.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR4Fv86RZYjziu0-rg37Pxw5AptY61qs4',
    appId: '1:257163398101:ios:aaaf15d350aa93037e8b5c',
    messagingSenderId: '257163398101',
    projectId: 'notes-flutter-290323',
    storageBucket: 'notes-flutter-290323.appspot.com',
    iosClientId: '257163398101-at9ic8drpnq13dibm6a6fmr0m89uhael.apps.googleusercontent.com',
    iosBundleId: 'com.droidtechlab.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR4Fv86RZYjziu0-rg37Pxw5AptY61qs4',
    appId: '1:257163398101:ios:aaaf15d350aa93037e8b5c',
    messagingSenderId: '257163398101',
    projectId: 'notes-flutter-290323',
    storageBucket: 'notes-flutter-290323.appspot.com',
    iosClientId: '257163398101-at9ic8drpnq13dibm6a6fmr0m89uhael.apps.googleusercontent.com',
    iosBundleId: 'com.droidtechlab.notes',
  );
}
